version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - pip install --upgrade aws-sam-cli
      - npm install -g typescript
      - npm install

  build:
    commands:
      - npm run build  # This should compile your TypeScript to JavaScript
      - sam build -t template.yaml
      - sam package --s3-bucket ${PACKAGE_BUCKET} --output-template-file packaged.yaml

artifacts:
  files:
    - packaged.yaml
  discard-paths: yes

cache:
  paths:
    - 'node_modules/**/*'
