version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - pip install --upgrade aws-sam-cli
      - npm install

  build:
    commands:
      - sam build -t template.yaml
      - sam package --s3-bucket ${PACKAGE_BUCKET} --output-template-file packaged.yaml --region ${AWS_REGION}

artifacts:
  files:
    - packaged.yaml
  discard-paths: yes

cache:
  paths:
    - 'node_modules/**/*'
